version: '3.8'

services:
  mssql:
    container_name: ticket-booking-sql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Abc12345      # <--- Mật khẩu mới (Đủ mạnh)
    ports:
      - "1433:1433"
    volumes:
      - sql_data_vol:/var/opt/mssql
    restart: always
  # THÊM SERVICE REDIS VÀO ĐÂY
  redis:
    container_name: ticket-booking-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
volumes:
  sql_data_vol: