version: '3.8'

services:
  mssql:
    container_name: ticket-booking-sql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Abc12345      # <--- Mật khẩu mới (Đủ mạnh)
    ports:
      - "1433:1433"
    volumes:
      - sql_data_vol:/var/opt/mssql
    restart: always
  # THÊM SERVICE REDIS VÀO ĐÂY
  redis:
    container_name: ticket-booking-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: ticket-booking-elastic
    environment:
      - discovery.type=single-node # Chạy 1 node cho môi trường Dev.
      - xpack.security.enabled=false # Tắt bảo mật (HTTPS/User) để dev cho nhanh.
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # Giới hạn RAM (Java rất ngốn RAM).
    ports:
      - "9200:9200" # Cổng API.
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: always

  # DASHBOARD UI (Để xem dữ liệu trong Elastic)
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: ticket-booking-kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    restart: always

volumes:
  sql_data_vol: